### ISSUE TITLE
Protobuf errors with redis provider

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [TurnerSoftware/CacheTower#103]
I'm getting protobuf serializer errors using the redis provider when caching custom types. Is this expected? Do I need to follow protobuf doc to create serializers, or pre-serialize my data into string for example?

I don't have an error example at the moment, I can get one later for you if you need to see it. But it's basically "serializer not available for model (default)".

**Comment by Turnerj** [comment]
Hey @ErikPilsits-RJW - thanks for raising an issue! There shouldn't be any issues with serializing with protobuf if you are decorating your types like protobuf.net requires:

- ProtoContractAttribute on type
- Each property to have a ProtoMemberAttribute on it

https://github.com/TurnerSoftware/CacheTower/blob/a3f9c9884b4007bbacea24e3e65a8cc3b3d0211b/tests/CacheTower.Tests/Providers/ComplexTypeCachingObjects.cs#L10-L18

I did just realise though that my documentation doesn't say that anywhere so that is definitely on me for not being clear. I'll look at updating the documentation soon.

Now if you do have those attributes and are still having issues, please provide me with the model that is causing the issue to see if I can recreate it.

**Comment by ErikPilsits-RJW** [comment]
Thanks, I will try this out shortly. However I've got another issue, and I can open a bug report if you like. I'm trying a basic redis backed setup. SetAsync works, but GetOrSetAsync is not setting the value into redis. It is setting the value into memory however, and does return the expected value.

If I remove the redis extensions, then it works and does set the value into redis. However I can't really use redis without them, since I have scaled app services in azure. Note I need to remove _both_ redis extensions, having either one will cause the problem.

Here's a basic reproducer I mocked up in linqpad.

```csharp
var redisConnection = ConnectionMultiplexer.Connect("-azure-cnxn-string-");

var c = new CacheStack(
    new ICacheLayer[]
    {
        new MemoryCacheLayer(),
        new RedisCacheLayer(redisConnection, 0)
    },
    new ICacheExtension[]
    {
        new AutoCleanupExtension(TimeSpan.FromMinutes(5)),
        new RedisLockExtension(redisConnection, 0),
        new RedisRemoteEvictionExtension(redisConnection)
    });

// works
var result1 = c.SetAsync("setasync", "hello world", TimeSpan.FromHours(24)).GetAwaiter().GetResult();
// doesn't work
var result2 = c.GetOrSetAsync<string>("getorsetasync", old => Task.FromResult("hello world"), new CacheSettings(TimeSpan.FromMinutes(2))).GetAwaiter().GetResult();
result1.Dump();
result2.Dump();
```

**Comment by Turnerj** [comment]
Thanks for that detailed information about this other issue. It will be easiest to track it in a second issue, especially if the issues aren't caused by the some underlying problem, however I should be able to look into this in the next day or two.

**Comment by ErikPilsits-RJW** [comment]
Thanks. The suggestion for the protobuf attributes _seems_ to have resolved the error, however I'll need to see it in redis to be sure, which requires resolving the other issue. I'll open a new issue for that now.

**Comment by ErikPilsits-RJW** [comment]
All good on the protobuf front after adding the attributes.

**Comment by Turnerj** [comment]
Awesome, glad that solves this issue. Will definitely update the readme to better indicate this. 🙂
