### ISSUE TITLE
Race condition and problem with GetOrAdd background refresh

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [TurnerSoftware/CacheTower#118]
Thank you for the latest updates with fixes to dependencies! I'm testing some things today and I think I found a small race condition, and a bug.

First the race, which only seems to happen with Redis (at least, it's the only place I can observe it). It's a really small one, probably unlikely to happen in the real world, because logically you wouldn't do this. Basically, if a cache entry exists in Redis but not in local memory, so for example if the app is restarted, and you call GetOrAddAsync _immediately_ followed by EvictAsync on the same cache key, the entry is not evicted. I think there's a race between the background refresh in GetOrAdd and the eviction.

_... After I wrote that I checked on something else, and while it is a race condition, it's caused by the issue below, which is kind of a big deal, keep reading..._

Now the bug... In GetOrAdd, you check stale date to trigger a background refresh. In my case stale time is 0. Here's that check.
```csharp
if (cacheEntry.GetStaleDate(settings) < currentTime)
{
}

//----

public DateTime GetStaleDate(CacheSettings cacheSettings)
{
	return Expiry - cacheSettings.TimeToLive + cacheSettings.StaleAfter;
}
```

But isn't `Expiry - cacheSettings.TimeToLive` always the date the entry was created? And therefore always less than currentTime? This triggers a background refresh on _every access_ through GetOrAdd if stale time is 0 (at worst), and after staleTime if staleTime is greater than 0 (at best). But it basically ignores the expiry for refreshes.

I've confirmed this, because if I set a stale time, then I can no longer reproduce the race condition. And because the following always prints "refresh" in separate runs within the 2 minute expiration.
```csharp
var result2 = await c.GetOrSetAsync<string>("getorsetasync", old =>
{
    Console.WriteLine("refresh");
    return Task.FromResult("hello world");
}, new CacheSettings(TimeSpan.FromMinutes(2)));
```

And this prints "refresh" _twice_.
```csharp
var result2 = await c.GetOrSetAsync<string>("getorsetasync", old =>
{
    Console.WriteLine("refresh");
    return Task.FromResult("hello world");
}, new CacheSettings(TimeSpan.FromMinutes(2)));

await Task.Delay(500);

result2 = await c.GetOrSetAsync<string>("getorsetasync", old =>
{
    Console.WriteLine("refresh");
    return Task.FromResult("hello world");
}, new CacheSettings(TimeSpan.FromMinutes(2)));
```

**Comment by Turnerj** [comment]
> First the race, which only seems to happen with Redis (at least, it's the only place I can observe it). It's a really small one, probably unlikely to happen in the real world, because logically you wouldn't do this. Basically, if a cache entry exists in Redis but not in local memory, so for example if the app is restarted, and you call GetOrAddAsync immediately followed by EvictAsync on the same cache key, the entry is not evicted. I think there's a race between the background refresh in GetOrAdd and the eviction.

Yeah, that sounds possible. When there is a cache miss at one layer but a cache hit at a deeper layer, the cache is back populated to lowest (or highest depending how you think about it) layer. So if Redis has the value but in-memory doesn't, it will attempt to set the value in the in-memory layer.

Because this operation happens in the background, awaiting `GetOrAddAsync` would end and the `EvictAsync` would start. When an eviction starts, it just calls the underlying cache layers to evict immediately - there is no locking or lock checks involved here to confirm that it can evict. That said, maybe it should, maybe evictions should actually share the same lock that refreshing uses, that wait it would prevent this race condition.

As `EvictAsync` isn't the normal "hot path" (`GetOrAddAsync` is), having this extra logic wouldn't be an issue in my opinion.

> But isn't `Expiry - cacheSettings.TimeToLive` always the date the entry was created? And therefore always less than currentTime? 

Yeah, you're right. The logic there seems to work under the assumption there is always a stale time period. On one hand, it doesn't seem like a bad idea - the cache returns fast but it always ensures the data in the background is the freshest.

> This triggers a background refresh on _every access_ through GetOrAdd if stale time is 0 (at worst), and after staleTime if staleTime is greater than 0 (at best). But it basically ignores the expiry for refreshes.

Yeah so this is the "on the other hand" - it is technically correct but probably unintended in most cases. If someone is saying they have a stale time of 0, they probably aren't implying constant background refreshes but rather having a fixed expiry where things are queried again.

Not that a fixed expiry with no stale time is inherently bad, a stale time of some amount is very useful to keep applications performing fast. I'd probably encourage the use of _any_ stale time than none at all.

> I've confirmed this, because if I set a stale time, then I can no longer reproduce the race condition. And because the following always prints "refresh" in separate runs within the 2 minute expiration.
> 
> And this prints "refresh" twice.

Part of me wouldn't necessarily say it is a bug but definitely can be an unintended side effect. I'll probably look at changing the logic so that a 0 stale time is treated that no background refreshes happen. This makes an expired-miss lock the cache but may likely be the more intended scenario.

**Comment by epilsits** [comment]
My gut expectation regarding expiry and stale time is that a background refresh would only happen when a request occurs between the expiry time and stale time. If there is no stale time, then yes, the next request would lock waiting. I think the cache should both improve application response time and reduce resource demand on the data source. With a small or zero stale time the app response would be improved but every request would trigger a queued background refresh. Not sure exactly how all those refreshes are sync'd with a lot of simultaneous requests, but the demand on the data source would certainly be high, possibly impacting non-cached requests. Something to consider.

**Comment by Turnerj** [comment]
So the refreshes themselves are designed to lock, preventing multiple requests going up the chain to avoid that high-demand scenario on the data source.

But yeah, really if the stale time is less than 10 seconds, it is probably way too low and will cause problems. In my own uses of the library, I have the stale time at about half of my time-to-live which itself is usually anywhere from 10 minutes to 1 hour (depending on the item being cached).

**Comment by epilsits** [comment]
Maybe I misinterpreted stale time... Is it intended to be the absolute time after which an entry will be refreshed in the background, but less than the actual expiry time? So if I would set a typical cache entry for 1 hour, and I wanted 30 minutes "grace", then in cachetower I would set stale for 1 hour and expired for 90 minutes?

I had initially thought of stale time as additional time past expiry, as in _added_ to expiry. So set expiry for 1 hour and stale for 30 minutes.

**Comment by Turnerj** [comment]
> Is it intended to be the absolute time after which an entry will be refreshed in the background, but less than the actual expiry time?

Yep, that was my intention with a stale time.

`TimeToLive`: The absolute amount of time before eviction from the cache will occur.
`StaleAfter`: The amount of time after which the cache is considered stale. It will still be served to clients but a background refresh will occur.

`TimeToLive` needs to be greater than `StaleAfter`. The closer these values are, the less likely a background refresh will occur. As you've found, `StaleAfter` can be 0 which then it is effectively treated as "always stale". It can be useful but also be unexpected behaviour.

I _think_ the names of these properties are pretty good but I definitely should beef up the IntelliSense documentation.

> So if I would set a typical cache entry for 1 hour, and I wanted 30 minutes "grace", then in cachetower I would set stale for 1 hour and expired for 90 minutes?

Yep! You'd set the `TimeToLive` for 1.5hrs (representing the maximum upper bound before removal) and set the `StaleAfter` to 1hr (before any refreshes are actually performed).

-----

With all this in mind, if you have any suggestions for clearer naming and documentation, let me know! This library has exploded with usage but I haven't had a huge amount of feedback. My own sites where I use this don't have huge amounts of traffic so I don't hit edge cases like others might.

**Comment by ErikPilsits-RJW** [comment]
I understand now. I agree some intellisense help and some additional explanation in the readme would be great. Pointing out some edge cases and improper usage would be helpful also.

Thanks for the explanation!
