### ISSUE TITLE
Is it possible to by pass a cache layer?

### ISSUE THREAD

**Issue by robertocpsilva1** [TurnerSoftware/CacheTower#128]
Is there a way to define different layers for different data types? 
Say we have CacheTower set up with two layers, memory and redis, but have some big objects we never want to store in memory what would be the recommended way to go about this?

We could workaround it in a few ways like having different CacheTowers defined with different layers but I wonder if there is something already in place like bypassing?

Cheers

**Comment by Turnerj** [comment]
Interesting usecase. I'd probably stick to separate CacheStacks though will think about it a little more to see if bypassing layers is achievable with little overhead.

**Comment by Turnerj** [comment]
After thinking about this more, I'm not sure layer bypassing is a good idea. I would say have a separate cache stacks for each scenario where you have logic that needs to be in different layers is the best idea.

To have the ability to skip layers requires storing additional metadata in either the layers or the cache stack so that when it performs a "back populate", it won't just bring your big object out from a further layer into the lower layers (eg. memory layers).

Depending how you want to go about it, whether you're using DI or not, may change how easy/hard it is for you. Assuming you're injecting the `ICacheStack<MyContext>` into your classes, it probably is easiest to have a `ICacheStack<LargeObjectsContext>` and `ICacheStack<SmallObjectsContext>` (though with whatever context names best suit your application/data).

It is probably annoying if you're needing both the small and large objects often as you'd need to keep injecting two values. You could wrap the cache stacks themselves into another singleton class you maintain to work around that if you wanted though, injecting this new class in your other classes and accessing a property for the cache for small objects and a property for the cache for large objects.

I'm going to close this issue now but if you have any other queries etc, feel free to open an issue. 🙂
