### ISSUE TITLE
Cache fails to retrieve empty Dictionary from Redis

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [TurnerSoftware/CacheTower#149]
This is a weird one. I get a null result retrieving an empty Dictionary from Redis. A Dictionary with values works fine.

Here's a repro. The .Dump() method is from LINQPad.

```csharp
async Task Main()
{
    var config = ConfigurationOptions.Parse("connect string");
    config.AllowAdmin = true;

    var conn = ConnectionMultiplexer.Connect(config);

    var lockOptions = new RedisLockOptions(databaseIndex: 7);
    var redisLayer = new RedisCacheLayer(conn, 8);

    var cache = new CacheStack(
        new ICacheLayer[]
        {
            redisLayer
        },
        new ICacheExtension[]
        {
            new AutoCleanupExtension(TimeSpan.FromMinutes(5)),
            new RedisLockExtension(conn, lockOptions)
        });

    await cache.EvictAsync("mykey");

    var d = await cache.GetOrSetAsync<Dictionary<string,string>>("mykey",
        old => Task.FromResult(new Dictionary<string,string>()),
        new CacheSettings(TimeSpan.FromMinutes(1), TimeSpan.FromMinutes(1)));
    
    d.Dump();

    d = await cache.GetOrSetAsync<Dictionary<string, string>>("mykey",
        old => Task.FromResult(new Dictionary<string, string>()),
        new CacheSettings(TimeSpan.FromMinutes(1), TimeSpan.FromMinutes(1)));

    // d is null here
    d.Dump();
}
```

**Comment by Turnerj** [comment]
For Redis caching, the values have to be serialized when sending them through. Internally I use the Protobuf format through the library protobuf-net to do this (though for some reason, I don't mention that in the readme which is bad). It seems that the Protobuf format doesn't have a way to differentiate between a `null` value and an empty collection - no data is still no data in this case.

Marc Gravell, the author of the protobuf-net library, expands on this in this Stack Overflow answer: https://stackoverflow.com/a/21632160/1676444

This issue was news to me! I knew that using Protobuf would mean that people would need to mark their classes etc with Protobuf attributes however my understanding was that the serialization would handle things like this correctly.

At this stage I'm not sure what to do. Protobuf seems like the best serialization strategy for performance, memory allocations and storage. It does suck though that an empty collection becomes `null` when deserializing. I want the cache to represent the value exactly as it was passed (so if you cache `null`, that is what is returned).

I could try and do something in the `RedisCacheLayer` itself where if the type is `Dictionary<,>` and Redis has the value as `null`, I either always instantiate it or instantiate when a certain option is configured on the layer. This though wouldn't fix it for any nested/complex types that have dictionaries on their own properties.

I think though in the end, I might just have to leave this bug in place and either better document the behaviour or hope that the Protobuf format will support not-null empty collections in the future.

**Comment by ErikPilsits-RJW** [comment]
That's interesting. It's definitely worth a note in your doc so people can prepare for it. It's not too difficult, just know that empty collections might return null.

**Comment by Turnerj** [comment]
Yeah, will update the readme soon. Probably will add some Intellisense docs for each of the cache layers soon too. Will leave this open until I've done both.

**Comment by Turnerj** [comment]
Updated the readme and inline docs to note this issue.
