### ISSUE TITLE
CacheSettings - default StaleAfter to TimeToLive if one isn't provided

### ISSUE THREAD

**Issue by vp89** [TurnerSoftware/CacheTower#161]
Currently if you only provide a TTL to CacheSettings, then all entries are always considered stale. This forces the user to always engage with this additional complexity and I can imagine would be a pretty common way the library is accidentally misused.

I suggest that the default value for StaleAfter should be TimeToLive and not 0, so only users who actually need staleness to exist as a distinct concept have to deal with it. Curious to hear your thoughts on this.

This would break users who want StaleAfter to be 0 and aren't currently explicitly passing that in, which does complicate things.

**Comment by Turnerj** [comment]
It is a funny one - I originally had it the other way but as a suggestion from someone else I asked to review my code, [I switched the behaviour to what we have now](https://github.com/TurnerSoftware/CacheTower/commit/6dd6b158bdb5ea80ec5090bb7ab35e95eef6b246#diff-1d6e2e6f924e30a0e2e741756db2430368a091ac8b8e471ee699f5bc4dc43290). I wonder though if I maybe misinterpreted the feedback and they meant the `StaleAfter` value was to be 0 but the behaviour was to be that there is no point when it is stale.

For the performance benefits a stale refresh provides, I do want to encourage people to use it but yeah, it does need to be clearer.

Maybe the value for `StaleAfter` needs to be nullable...

**Comment by Turnerj** [comment]
Hey, just FYI, I decided to tweak your change and have the value be nullable now. Wasn't sure about it at first but after playing around with it, I think it makes the concept clearer when looking at the `CacheSettings` type itself. This change still follows the general logic change we've discussed here - the default `CacheSettings` constructor treats it like there is no stale time rather than everything being stale automatically.
