### ISSUE TITLE
`RedisCacheLayer` should not be allowed in `RedisRemoteEvictionExtension`

### ISSUE THREAD

**Issue by Turnerj** [TurnerSoftware/CacheTower#164]
See https://github.com/TurnerSoftware/CacheTower/issues/163#issuecomment-824094255

While the main issue is that `RedisCacheLayer` shouldn't be allowed, it is reasonable to consider that no distributed caches should be allowed (though let's be honest, would someone use a different distributed cache if they used Redis for remote eviction?).

**Solution 1**

Loop over the cache layers and check if any are a `RedisCacheLayer` (eg. `cacheLayer is RedisCacheLayer`). Problem with this approach is that it is in a different library and referencing it would suck.

**Solution 2**

Have some sort of shared `IDistributedCacheLayer` in the main CacheTower library and use that as the check. This avoids the problem above with the only downside that we have an interface we don't really care about (all cache layers are treated the same otherwise).

**Comment by mgoodfellow** [comment]
Or, just occurred to me now - we can have the idea of capabilities on the `ICacheLayer`

There is nothing wrong which the interface defining something like:

```csharp
public interface ICacheLayer
{
      bool IsDistributed { get; }    // Name TBC - I guess the "IsXYZ" is the correct way to write it though
      /* other stuff */
}
```

Now when defining your layer you are adding:

```csharp
public class MyAwesomeCacheLayer 
{
      public IsDistributed => true;
}
```

There is always a fear of dirtying the API surface, however, I think in certain instances its important to "know" things about the implementation. Endless interfaces is one evil, and polluted interfaces is another - however, I think in this case this is less of one.

It reminds me of the NHibernate approach of writing a database driver:

https://github.com/nhibernate/NHibernate.MySqlConnector/blob/master/src/NHibernate.Driver.MySqlConnector/MySqlConnectorDriver.cs#L19

They used the base class approach here, but I think the interface defining it would also be OK?

**Comment by Turnerj** [comment]
Yeah, actually that would work. Probably is faster too as it isn't a type lookup.

**Comment by Turnerj** [comment]
One thought I had with this (not so much what you've said but the main premise of the issue) - what exactly would I label the file cache layer as? It _technically_ can be a distributed cache but practically it is unlikely to be used as one.

**Comment by mgoodfellow** [comment]
Actually, I have just been pondering this some more.

The fact the cache layer is distributed is not the reason it is being excluded in this instance from the remote eviction plugin.

Although there are definitely some rabbit holes / concerns around multiple cache stacks all evicting (the same) data from _distributed_ caches simultaneously due to this plugin (race condition), the actual reason we are excluding the redis layer here is because we can only block local evictions due to the pub/sub nature of the redis layer: https://github.com/TurnerSoftware/CacheTower/blob/3ac8eb7e3a7878e3905bfcf16ed10338c31540c4/src/CacheTower.Extensions.Redis/RedisRemoteEvictionExtension.cs#L108

Due to this, it would probably make more sense for `CacheTower.Extensions.Redis` to have a dependency on `CacheTower.Providers.Redis` and then perform the type check as discussed in Solution 1.

**Comment by mgoodfellow** [comment]
Regarding file cache layers - you could always make it more specific for use case - `LocalFileStoreCache` vs `DistributedFileStoreCache`, and it is therefore up to the user to make it clear whether these files will be shared among readers.

**Comment by Turnerj** [comment]
Ended up implementing this the interface way with `ILocalCacheLayer` and `IDistributedCacheLayer` for v0.12.0.
