### ISSUE TITLE
How to Background Refresh work?

### ISSUE THREAD

**Issue by azhe403** [TurnerSoftware/CacheTower#197]
### What does the bug do?

How to Background Refresh work?

### How can it be reproduced?

I has Inject cache stack to dependency

![image](https://user-images.githubusercontent.com/17938038/145169169-e33a2900-69f3-499e-ad5d-d83e57093fa3.png)

And then resolve service via constructor

![image](https://user-images.githubusercontent.com/17938038/145168854-b022b8ef-ce41-446f-a08f-6e75f996b5c6.png)

And json cache has created, but manifest.json is empty, any wrong here?

![image](https://user-images.githubusercontent.com/17938038/145169022-1dc3b85e-0e55-46d7-9a72-ef8fd72d7399.png)

I wait until staleAfter but no background refresh like in description.

Any example of ASP.NET Core usage? because no docs specific about this.

Thanks.

### Environment (if applicable)

- NuGet Package Version: 0.11.6
- .NET Runtime Version: .NET 6
- Operating System: Windows

**Comment by Turnerj** [comment]
Hey @azhe403 - thanks for raising the issue! I've been meaning to improve the documentation - just haven't been able to find the time currently.

So background refreshing works like:
- You request an item from the cache...
  - No entry is found (cache miss)
  - Your value factory (querying a URL) is called
  - The value is set on the different cache layers
  - The value is returned
- You request the item again later after the "staleAfter" time but before the entry is expired...
  - The non-expired entry is found
  - It is checked if it is stale (it is)
  - A background refresh is called (but not awaited)
  - The non-expired (stale) entry is returned
- You request the item again later after the background refresh has finished...
  - The non-expired entry is found
  - It is checked if it is stale (it isn't)
  - The non-expired non-stale entry is returned

Regarding the manifest file - that is because the manifest file itself is only saved one disposal of the `CacheStack`, typically when the application/webserver is shutdown/restarted. I am considering [having the manifest file save at regular intervals](https://github.com/TurnerSoftware/CacheTower/issues/187#issuecomment-907779681) though as that would help if the application or server crashes.

**Comment by azhe403** [comment]
oh, so if cache expired in 10 minutes, but stale after is 5 minutes and hit cache again in 6 minutes, cache with be updating automatically in background but still returned current cache because not yet expired, right?

**Comment by Turnerj** [comment]
> oh, so if cache expired in 10 minutes, but stale after is 5 minutes and hit cache again in 6 minutes, cache with be updating automatically in background but still returned current cache because not yet expired, right?

Bingo!

The idea behind all of this is that it takes pressure off your hot path (accessing your cached resource) while trying to keep the value relatively up-to-date.

One thing I should mention - because background refreshes happen outside the scope of your calling method, you can hit cases where things are disposed. I've got some information here about that: https://github.com/TurnerSoftware/CacheTower#avoiding-disposed-contexts
